name: Docker / Ubuntu 22.04 / Build and Test
run-name: docker-ubuntu-2204 performed by @${{ github.triggering_actor }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-2204-docker:
    name: gcc / ${{ matrix.build-type }} / ${{ matrix.sanitizer-type }}
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: galois
      CONTAINER_SRC_DIR: "/galois"
      CONTAINER_BUILD_DIR: "/galois/build"
      CONTAINER_WORK_DIR: "/galois"
      INTERACTIVE: ""
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        build-type: ['Release']
        sanitizer-type: ['nosan']

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: 'true'
        submodules: recursive

    - name: Set up environment variables
      timeout-minutes: 1
      run: |
        echo "UNAME=$(whoami)" >> $GITHUB_ENV
        echo "UID=$(id -u)" >> $GITHUB_ENV
        echo "GID=$(id -g)" >> $GITHUB_ENV
        echo "SRC_DIR=$(pwd)" >> $GITHUB_ENV
        echo "GALOIS_TEST_DISCOVERY_TIMEOUT=600" >> $GITHUB_ENV
        echo "IMAGE_VERSION=$(git log --pretty="%h" -1 Dockerfile.dev)" >> $GITHUB_ENV
        if [ ${{ matrix.sanitizer-type }} == 'san' ]; then
          echo "PANDO_CONTAINER_ENV=-e=GALOIS_EXTRA_CXX_FLAGS='\"-fsanitize=address -fsanitize=undefined\"'" >> $GITHUB_ENV
        fi
        cat $GITHUB_ENV

    - name: Configure
      timeout-minutes: 10
      run: |
        CONTAINER_CMD="make setup-ci" \
          CONTAINER_OPTS="-e=BUILD_TYPE=${{ matrix.build-type }}" \
          IMAGE_NAME="${{ env.IMAGE_NAME }}" \
          VERSION="${{ env.IMAGE_VERSION }}" \
          make docker

    - name: Build
      timeout-minutes: 15
      run: |
        CONTAINER_CMD="bash -c 'make -j8 || make || make'" \
          IMAGE_NAME="${{ env.IMAGE_NAME }}" \
          VERSION="${{ env.IMAGE_VERSION }}" \
          CONTAINER_WORKDIR="${{ env.CONTAINER_BUILD_DIR }}" \
          make docker

    - name: Run Tests
      timeout-minutes: 5
      run: |
        CONTAINER_CMD="make run-tests" \
          IMAGE_NAME="${{ env.IMAGE_NAME }}" \
          VERSION="${{ env.IMAGE_VERSION }}" \
          make docker
